/* confdefs.h */
#define PACKAGE_NAME "blitz"
#define PACKAGE_TARNAME "blitz"
#define PACKAGE_VERSION "0.10"
#define PACKAGE_STRING "blitz 0.10"
#define PACKAGE_BUGREPORT "blitz-support@lists.sourceforge.net"
#define PACKAGE_URL ""
#define PACKAGE "blitz"
#define VERSION "0.10"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define _compiler_name "c++"
#define _compiler_options ""
#define _os_name "Darwin MBP-2018-lyx.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64"
#define _config_date "Thu Jul 23 22:46:04 CST 2020"
#define _platform "x86_64-apple-darwin19.4.0"
#define HAVE_NAMESPACES /**/
#define HAVE_EXCEPTIONS /**/
#define HAVE_RTTI /**/
#define HAVE_MEMBER_CONSTANTS /**/
#define HAVE_EXPLICIT /**/
#define HAVE_MUTABLE /**/
#define HAVE_TYPENAME /**/
#define HAVE_NCEG_RESTRICT_EGCS /**/
#define HAVE_BOOL /**/
#define HAVE_CONST_CAST /**/
#define HAVE_STATIC_CAST /**/
#define HAVE_REINTERPRET_CAST /**/
#define HAVE_DYNAMIC_CAST /**/
#define HAVE_TEMPLATES /**/
#define HAVE_PARTIAL_SPECIALIZATION /**/
#define HAVE_PARTIAL_ORDERING /**/
#define HAVE_DEFAULT_TEMPLATE_PARAMETERS /**/
#define HAVE_MEMBER_TEMPLATES /**/
#define HAVE_MEMBER_TEMPLATES_OUTSIDE_CLASS /**/
#define HAVE_FULL_SPECIALIZATION_SYNTAX /**/
#define HAVE_FUNCTION_NONTYPE_PARAMETERS /**/
#define HAVE_TEMPLATE_QUALIFIED_BASE_CLASS /**/
#define HAVE_TEMPLATE_QUALIFIED_RETURN_TYPE /**/
#define HAVE_EXPLICIT_TEMPLATE_FUNCTION_QUALIFICATION /**/
#define HAVE_TEMPLATES_AS_TEMPLATE_ARGUMENTS /**/
#define HAVE_TEMPLATE_KEYWORD_QUALIFIER /**/
#define HAVE_TEMPLATE_SCOPED_ARGUMENT_MATCHING /**/
#define HAVE_TYPE_PROMOTION /**/
#define HAVE_USE_NUMTRAIT /**/
#define HAVE_ENUM_COMPUTATIONS /**/
#define HAVE_ENUM_COMPUTATIONS_WITH_CAST /**/
#define HAVE_COMPLEX /**/
#define HAVE_COMPLEX_FCNS /**/
#define HAVE_CSTRING 1
#define HAVE_NUMERIC_LIMITS /**/
#define HAVE_CLIMITS /**/
#define HAVE_VALARRAY /**/
#define HAVE_COMPLEX_MATH1 /**/
#define HAVE_IEEE_MATH /**/
#define MATH_FN_IN_NAMESPACE_STD /**/
#define MATH_ABSINT_IN_NAMESPACE_STD /**/
#define HAVE_COMPLEX_MATH_IN_NAMESPACE_STD /**/
#define ISNAN_IN_NAMESPACE_STD /**/
#define HAVE_STD /**/
#define HAVE_STL /**/
#define HAVE_RUSAGE /**/
